version: '1.0'
stages:
  - checkout
  - package
  - test  
  - deployment
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: checkout
  flaskr:
    title: Building Docker Image
    type: build
    stage: package
    image_name: stabon/flaskr
    working_directory: ./
    tags:
      - latest
      - ${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}
      - ${{CF_SHORT_REVISION}}
    dockerfile: Dockerfile
  unit_tests:
    title: Running Unit tests
    image: '${{flaskr}}'
    stage: test 
    commands: 
      - pip install pytest
      - pytest
  approval:
    title: Deploy to Prod?
    type: pending-approval
    stage: deployment
    timeout:
      finalState: denied
  deploy:
    title: Deploy to K8s
    image: codefresh/cf-deploy-kubernetes:master
    stage: deployment
    commands:
      - /cf-deploy-kubernetes deployment.yaml
    env:
      name: k8s
      endpoints:
      - name: Flaskr
        url: http://fr.sbko.io
      type: kubernetes
      change: Updated
      filters:
      - cluster: digitalOcean@k8s01demo
        namespace: flaskr
    environment:
    - KUBECONTEXT=digitalOcean@k8s01demo
    - KUBERNETES_NAMESPACE=flaskr
